_index:
    pattern:  /{page}
    defaults: { _controller: EFFlickrBundle:Index:index, page: 1 }
    requirements:
        page:  \d+

_search:
    pattern: /search
    defaults: { _controller: EFFlickrBundle:Index:search }